"""Run the decision instrument over the land-enterprise candidate list.

    python scripts/land_enterprise_inventory.py                      # report to stdout
    python scripts/land_enterprise_inventory.py --interview-sheet    # the session worksheet
    python scripts/land_enterprise_inventory.py --first-pass         # the 16-decision subset
    python scripts/land_enterprise_inventory.py --out docs/x.md      # write instead of print

The candidate list carries QUESTIONS ONLY (see `aigov.instances.land_enterprise`), so the
inventory report is expected to come back entirely UNDECIDABLE with every gap named. That is the
pre-elicitation state, and printing it is the point: it shows exactly which answers the session
has to produce before any verdict exists.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from aigov.answers import (                                                      # noqa: E402
    AnswersError, answered_ids, load_answers, render_template,
)
from aigov.decisions import build_inventory, interview_questions, render_report  # noqa: E402
from aigov.instances.land_enterprise import (                                    # noqa: E402
    CANDIDATES, FIRST_PASS, FIRST_PASS_IDS, SUSPECTED_COMPOUND_IDS, phase_of,
)


def candidate_list(decisions) -> str:
    """The flat list, for the user to strike through / reword / add to."""
    first = set(FIRST_PASS_IDS)
    compound = set(SUSPECTED_COMPOUND_IDS)
    # NOTE: every block below must sit under a `## ` heading. The ba-beautify parser
    # (skills/ba-beautify/scripts/document_parser.py) skips all content before the first
    # `## ` and drops any block while no section is open, so a heading-less document
    # converts to an empty .docx. Verified by kill-test 2026-08-12.
    lines = [
        "# Candidate decision list — family land enterprise (DRAFT, for correction)",
        "",
        "## How to use this list",
        "",
        "> Generated by `scripts/land_enterprise_inventory.py --candidate-list`. Drafted by Claude",
        "> so the inventory session is CORRECTION rather than composition. Nothing here is",
        "> elicited — it is a guess at the shape of decisions an enterprise like this recurs on,",
        "> and it is wrong in ways only you can see.",
        "",
        "**How to use it.** Strike out what you do not face. Reword what is not how you'd put it.",
        "Add what a drafter could not know — that is where the value is. Then work the worksheet.",
        "",
        "**No answers are drafted.** Frequencies, costs, market availability, roles and",
        "consequences are ELICITED fields; the instrument refuses to invent them and so does this",
        "list. Run without `--candidate-list` and every decision comes back `UNDECIDABLE` with the",
        "missing answers named. That is correct, not broken.",
        "",
        "**The order carries no structure.** Groups are computed from couplings you affirm, never",
        "proposed here — proposing them would import the template this whole family exists to avoid.",
        "",
        "**SCREENING** decisions recur across candidates, so a real frequency exists and a genuine",
        "INTERNALIZE verdict is reachable. **COMMITMENT** decisions are taken once, so expect",
        "MARKET or HYBRID unless private information or a missing market carries them — that is the",
        "arithmetic working, not a defect.",
        "",
        f"`!` = suspected compound, consider splitting ({', '.join(SUSPECTED_COMPOUND_IDS)})",
        "",
        "## Candidate decisions",
        "",
        "| mark | id | phase | decision |",
        "|---|---|---|---|",
    ]
    for d in decisions:
        mark = "!" if d.id in compound else "&nbsp;"
        lines.append(f"| {mark} | {d.id} | {phase_of(d.id)} | {d.question} |")
    lines += [
        "",
        f"Drafted: {len(decisions)} · first pass: {len(first)} · family bar: >=15 with all four",
        "sourcing inputs answered.",
    ]
    return "\n".join(lines)


def interview_sheet(decisions) -> str:
    """The worksheet the correction session is actually run from."""
    lines = [
        "# Decision-inventory worksheet — family land enterprise",
        "",
        "## How to use this worksheet",
        "",
        "> Generated by `scripts/land_enterprise_inventory.py --interview-sheet`. Every question",
        "> below is one `aigov.decisions` needs answered before it will issue any verdict. Answer",
        "> in your own units and your own words. **No answer is defaulted** — an unanswered field",
        "> is reported as a named gap, never guessed.",
        "",
        "**Correct the list first.** Delete decisions you do not actually face, reword any that",
        "are not how you would put it, and add the ones a drafter could not know. Only then start",
        "answering. A decision drafted wrong and answered carefully is worse than one deleted.",
        "",
        "**Roles, never names** — 'who answers for this' takes a role or an unfilled slot.",
        "",
        f"Suspected compound (consider splitting before answering): "
        f"{', '.join(SUSPECTED_COMPOUND_IDS)}",
        "",
    ]
    for d in decisions:
        qs = interview_questions(d)
        lines.append(f"## {qs[0]}")
        lines.append("")
        lines.append(f"*{phase_of(d.id)}*"
                     + ("  ·  **suspected compound — split before answering**"
                        if d.id in SUSPECTED_COMPOUND_IDS else ""))
        lines.append("")
        lines.extend(q.strip() and f"- {q.strip().lstrip('- ')}" or "" for q in qs[1:])
        lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--interview-sheet", action="store_true",
                    help="emit the session worksheet instead of the inventory report")
    ap.add_argument("--candidate-list", action="store_true",
                    help="emit the flat candidate list for correction")
    ap.add_argument("--first-pass", action="store_true",
                    help="restrict to the recommended first-pass subset")
    ap.add_argument("--answers-template", action="store_true",
                    help="emit a blank answers file to fill in (keep it OUTSIDE this repo)")
    ap.add_argument("--answers", type=Path, default=None,
                    help="path to a filled-in answers file; runs the inventory on real answers")
    ap.add_argument("--allow-answers-inside-repo", action="store_true",
                    help="override the privacy refusal. ONLY for fixtures with nothing real in them")
    ap.add_argument("--out", type=Path, default=None, help="write to this path instead of stdout")
    args = ap.parse_args(argv)

    decisions = FIRST_PASS if args.first_pass else CANDIDATES

    if args.answers:
        try:
            decisions = load_answers(
                args.answers,
                {d.id: d.question for d in decisions},
                allow_inside_repo=args.allow_answers_inside_repo,
            )
        except AnswersError as exc:
            print(f"REFUSED: {exc}", file=sys.stderr)
            return 2

    if args.answers_template:
        text = render_template(decisions, phase_of=phase_of)
    elif args.candidate_list:
        text = candidate_list(decisions)
    elif args.interview_sheet:
        text = interview_sheet(decisions)
    else:
        report = build_inventory(decisions)
        text = render_report(report)
        answered = answered_ids(decisions)
        text += (
            f"\n\nSUMMARY\n"
            f"  decisions in scope       {len(decisions)}\n"
            f"  fully answered           {len(answered)} of {len(decisions)}"
            f"   (family bar: >=15)\n"
            f"  sourcing verdicts        {len(report.verdicts)}\n"
            f"  confirmed capabilities   {len(report.capabilities)}\n"
            f"  undecided (named gaps)   {len(report.undecided)}\n"
            f"  no accountable role      {len(report.unowned)}\n"
            f"  no checking requirement  {len(report.unassured)}\n"
            f"  inventory complete       {report.is_complete}\n"
        )

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text + "\n", encoding="utf-8")
        print(f"wrote {args.out} ({len(text.splitlines())} lines)")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
